dataset:
  data_path: "./data/cropped_data/"
  cropped: 1
  random_seed: 123
  shuffle: 1
  fold: 1
  batch_size: 2
  augmentation: 1
  val_aug: 1
  normalize_imagenet: 0
  automatic_normalize: 0

model:
  name: "model"
  encoder_name: 'nvidia/mit-b5'
  exp_name: '1_fold'
  num_classes: Null
  multichannel: 1

opt:
  lr: 0.0001
  es_patience: 8
  lr_patience: 6
  epochs: 200
  num_workers: 24
  logit_loss: 0
  weight: [1.1, 1, 1]  #Null
  from_last_to_unfreeze: 10000
  save_each_epoch: 0
  crossentropy_loss: 1
  ignore_index: Null
  processor: 1
