wandb:
  online: 1

dataset:
  data_path: "./data/cropped_data/"
  random_seed: 123
  shuffle: 1
  fold: 1       # change to switch folder for training
  batch_size: 2
  augmentation: 1
  val_aug: 1
  normalize_imagenet: 0
  automatic_normalize: 0

model:
  name: "segformer"
  encoder_name: 'nvidia/mit-b5'
  exp_name: '1_fold'
  num_classes: 2
  checkpoint: Null

opt:
  lr: 0.0001
  es_patience: 8
  lr_patience: 6
  epochs: 200
  num_workers: 24
  logit_loss: 0
  weights: [1, 1.1, 1, 2]
  from_last_to_unfreeze: 10000
  save_each_epoch: 0
  crossentropy_loss: 1
  ignore_index: Null
  processor: 1
  method: 'bayes'
  metric_name: 'Validation IoU'
  metric_goal: 'maximize'
