dataset:
  data_path: "./data/cropped_data/"
  cropped: 1
  random_seed: 123
  shuffle: 1
  fold: 1
  batch_size: 2
  augmentation: 1
  val_aug: 1
  normalize_imagenet: 0
  automatic_normalize: 0
  pil_version: 0
  #rescale_befor_norm: 0

model:
  name: "model"
  encoder_name: 'nvidia/mit-b4'
  exp_name: 'test'
  remove_aux: 0
  num_classes: Null
  multichannel: 1

opt:
  lr: 0.0001
  es_patience: 15
  lr_patience: 6
  epochs: 200
  num_workers: 0
  logit_loss: 0
  weight: Null  #Null
  from_last_to_unfreeze: 10000
  save_each_epoch: 0
  crossentropy_loss: 1
  ignore_index: Null
  processor: 1
